### PR TITLE
Added .NET Standard support

### PR DESCRIPTION
**Pull request by drjaydenm**
Hi there, I would love to use this library in my game engine, however I am running in .NET Core and cannot currently use the package due to the .NET Framework dependency.

I have migrated the projects across to the .NET SDK project format and setup .NET standard configs for the core library project, as well as the test project. The sample and generator projects would require a little bit more work, but shouldn't block the core library from being moved across.

If I have overlooked anything, or if there is anything that needs fixing up, please let me know.

### CODE REVIEW

**Comment by drjaydenm** [comment]
Took a quick look at the failing build, but it also seems to be failing for master branch too

**Comment by Starnick** [comment]
AssimpNet has supported net standard for some time. Development happens here:

https://bitbucket.org/Starnick/assimpnet/src/master/

https://www.nuget.org/packages/AssimpNet/

I do not own this github repository.

**Comment by drjaydenm** [comment]
Ahh great, looks like I can use that out of the box! Thanks for linking that.

I wonder if there is anything that can be done to make it a little clearer that this is the incorrect repo? I felt like I searched around quite a bit, but never came across the bitbucket repo anywhere.

**Review by kimkulling — APPROVED** [review]

**Comment by Starnick** [comment]
Yes it's a shame...Google search puts the bit bucket repo 4th in my results. I figure most people know where to find it because of my nuget releases which have a link back. After Google code I chose bit bucket because of the free private repositories there. Although that seems moot now since git hub has that feature too. But I'm not going to suddenly start using github for my main development to satisfy what other people think about one of my projects though.

Once upon a time the assimp repo had a link back to bitbucket, but that does not seem to be the case anymore. This repo is so out of date it should not be taking PRs like this. There was a great effort to get us onto netstandard and cross platform straight out of the box two years ago!

@kimkulling it would be great if you actually gave me ownership of this repo and I'll make it into a mirror that I'll update from time to time. I assume you want it kept under the assimp organization  (I'm assuming it's one and not a dummy account), so I don't know if that means true ownership or just admin rights.

And at the risk of sounding difficult, the "branding" was really assimpnet, not assimp-net. It would be more consistent with the actual nuget releases I do and the bitbucket repo. I don't know if renaming breaks things on github or not.

**Comment by kimkulling** [comment]
Good idea!

**Pull request merged**
